[YAML]
# Xeno 地区池：只引用订阅中的节点名称，不保存节点凭证；无 regex/filter/include-all。
+proxy-groups:
  - name: "🇭🇰 香港节点"
    type: url-test
    proxies: ["🎞️ 1.0x 🇭🇰 香港 HK - S1", "🎞️ 1.0x 🇭🇰 香港 HK - 0", "🎞️ 1.0x 🇭🇰 香港 HK - o2", "🎞️ 1.0x 🇭🇰 香港 HK - o3", "🎞️ 1.0x 🇭🇰 香港 HK - o4", "🎞️ 1.0x 🇭🇰 香港 HK - OC", "[其他不能用再用这个] HK 🎞️ 🇭🇰 香港", "[其他不能用再用这个] HK 🏠 🇭🇰 香港"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇹🇼 台湾节点"
    type: url-test
    proxies: ["🎞️ 1.0x 🇹🇼 台湾 TW - S1", "🎞️ 1.0x 🇹🇼 台湾 TW - 0", "🎞️ 1.0x 🇹🇼 台湾 TW - o2", "🎞️ 1.0x 🇹🇼 台湾 TW - o3", "🎞️ 1.0x 🇹🇼 台湾 TW - o4", "🎞️ 1.0x 🇹🇼 台湾 TW - OC", "[其他不能用再用这个] TW 🎞️ 🇹🇼 台湾", "[其他不能用再用这个] TW 🏠  🇹🇼 台湾 TW"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇯🇵 日本节点"
    type: url-test
    proxies: ["🎞️ 1.0x 🇯🇵 日本 JP - 0", "🎞️ 1.0x 🇯🇵 日本 JP - o2", "🎞️ 1.0x 🇯🇵 日本 JP - o3", "🎞️ 1.0x 🇯🇵 日本 JP - o4", "🎞️ 1.0x 🇯🇵 日本 JP - OC", "[其他不能用再用这个] JP 🎞️ 1.0x 🇯🇵 日本", "[其他不能用再用这个] JP 🏠 2.0x 🇯🇵 日本", "🛰 [星链] 2.0x 🇯🇵 日本 JP - 0", "🛰 [星链] 2.0x 🇯🇵 日本 JP - o2", "🛰 [星链] 2.0x 🇯🇵 日本 JP - o3", "🛰 [星链] 2.0x 🇯🇵 日本 JP - o4", "🛰 [星链] 2.0x 🇯🇵 日本 JP - OC", "[其他不能用再用这个] JP 🛰 2.0x 🇯🇵 日本"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇺🇸 美国节点"
    type: url-test
    proxies: ["🎞️ 1.0x 🇺🇸 美国 US - 0", "🎞️ 1.0x 🇺🇸 美国 US - o2", "🎞️ 1.0x 🇺🇸 美国 US - o3", "🎞️ 1.0x 🇺🇸 美国 US - o4", "🎞️ 1.0x 🇺🇸 美国 US - OC", "[其他不能用再用这个] US 🎞️ 1.0x 🇺🇸 美国", "[其他不能用再用这个] US 🏠 1.0x 🇺🇸 美国"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇭🇰 香港家宽"
    type: url-test
    proxies: ["🏠 [家宽] 1.0x 🇭🇰 香港 HK - S1", "🏠 [家宽] 1.0x 🇭🇰 香港 HK - 0", "🏠 [家宽] 1.0x 🇭🇰 香港 HK - o2", "🏠 [家宽] 1.0x 🇭🇰 香港 HK - o3", "🏠 [家宽] 1.0x 🇭🇰 香港 HK - o4", "🏠 [家宽] 1.0x 🇭🇰 香港 HK - OC"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇹🇼 台湾家宽"
    type: url-test
    proxies: ["🏠 [家宽] 1.0x 🇹🇼 台湾 TW - 0", "🏠 [家宽] 1.0x 🇹🇼 台湾 TW - o2", "🏠 [家宽] 1.0x 🇹🇼 台湾 TW - o3", "🏠 [家宽] 1.0x 🇹🇼 台湾 TW - o4", "🏠 [家宽] 1.0x 🇹🇼 台湾 TW - OC"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇯🇵 日本家宽"
    type: url-test
    proxies: ["🏠 [家宽] 2.0x 🇯🇵 日本 JP - 0", "🏠 [家宽] 2.0x 🇯🇵 日本 JP - o2", "🏠 [家宽] 2.0x 🇯🇵 日本 JP - o3", "🏠 [家宽] 2.0x 🇯🇵 日本 JP - o4", "🏠 [家宽] 2.0x 🇯🇵 日本 JP - OC"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
  - name: "🇺🇸 美国家宽"
    type: url-test
    proxies: ["[不保Tiktok] 🏠 [家宽] 1.0x 🇺🇸 美国 US - 0", "[不保Tiktok] 🏠 [家宽] 1.0x 🇺🇸 美国 US - o2", "[不保Tiktok] 🏠 [家宽] 1.0x 🇺🇸 美国 US - o3", "[不保Tiktok] 🏠 [家宽] 1.0x 🇺🇸 美国 US - o4", "[不保Tiktok] 🏠 [家宽] 1.0x 🇺🇸 美国 US - OC"]
    url: "https://www.gstatic.com/generate_204"
    interval: 120
    tolerance: 100
    lazy: false
