[YAML]
proxy-groups*:
  where:
    name: '/Claude\.Ai$/'
  set:
    +proxies:
      - "🇯🇵 日本家宽"
      - "🇺🇸 美国家宽"
      - "🇹🇼 台湾家宽"
      - "🇭🇰 香港家宽"
      - "🇯🇵 日本节点"
      - "🇺🇸 美国节点"
      - "🇹🇼 台湾节点"
      - "🇭🇰 香港节点"
